### ISSUE TITLE
Enhancement: Webhooks

### ISSUE THREAD

**Issue by ghostlylake** [TheNoob27/starboard-issues#1]
Add a webhook to post any issues here to the support server.

**Comment by TheNoob27** [comment]
I was actually going to add git webhooks so you guys could see what i was doing
like i LITERALLY WAS JUST thinking about it before i opened this repository
I'll mess around with it later

**Comment by TheNoob27** [comment]
Okay that's done, i could possibly add it to my other repo's but who knows :eyes:

**Comment by ghostlylake** [comment]
POGGERS

**Comment by Hoi0007** [comment]
make it an announcement channel so we can follow the github updates, also weeb mode when
