### ISSUE TITLE
Starboard should be able to save starred messages within threads

### ISSUE THREAD

**Issue by ozyx** [TheNoob27/starboard-issues#17]
Currently, Starboard does not detect starred messages within threads (probably because the bot cannot see the thread without explicitly joining it). Not sure if there is any programmatic way to solve this via Discord API at this point, but would be good functionality to keep the bot consistent.

I also tried explicitly adding the message using `star save <messageId>` but Starboard replied with "`null`", so this is also not working.

**Comment by lewisfm** [comment]
Starboard's still using an older version of the API without thread support, but once it updates it should fix the problems. Also, the fact that it's replying `null` to your command is definitely a bug, and hopefully it'll be fixed soon.

**Comment by TheNoob27** [comment]
In case it has not been clear for some reason, yes - I am indeed working on this.

**Comment by maddie-wang** [comment]
Is it fixed yet! Really wanting this feature. Burning need!!!!

**Comment by maddie-wang** [comment]
so many goodies in threads cant save it, so sad D:

**Comment by maddie-wang** [comment]
no other bot allows me to save great things in threads

**Comment by maddie-wang** [comment]
@TheNoob27

**Comment by ozyx** [comment]
@maddie-wang Carl-bot actually does this: https://docs.carl.gg/utilities/starboard/
