### ISSUE TITLE
Message duplication

### ISSUE THREAD

**Issue by R3Ked** [TheNoob27/starboard-issues#18]
Sometimes starboard sends the same message to the starboard multiple times. I've seen this happen three times, and in all three instances, the duplicated message was in the same channel every time.
![duplication](https://user-images.githubusercontent.com/20342336/145691772-8d5dc1ef-c5ac-4224-b363-4d82c6c14838.png)
It also doesn't always happen if the channel has a starred message.
![undupe](https://user-images.githubusercontent.com/20342336/145691886-9e7eebc9-abe9-4c6f-b673-5b14edf83674.PNG)

**Comment by ghostlylake** [comment]
This is a known issue, reacting on the duplicates should remove them.

**Comment by R3Ked** [comment]
Can confirm it does.
