### ISSUE TITLE
Multiple starboards with multiple blacklists/whitelists

### ISSUE THREAD

**Issue by tswallen** [TheNoob27/starboard-issues#20]
Hey Noob

Really love your bot, you did super well making it! I'm trying to do something and need your help...

 So we have these categories and channels on Discord:
 
 ==TOP MEMES==
 #admin-1-picks
 #admin-2-picks
 #community-choice
 
 ==Submissions==
 #dog-memes
 #cat-memes
 #fish-memes
 
 So what I want to do is simple. I want any user to be able to add stars to any of the memes in the "Submissions" category (the 3 memes channels). If that user has the role of "@member" then if the meme gets enough stars it goes to #community-choice. If the meme is starred once by @admin-1 it goes to #admin-1-picks and if it's starred by @admin-2 it goes to #admin-2-picks.

How can I achieve this?
Thanks

**Comment by TheNoob27** [comment]
this seems to be a personal problem, better fit for support in the bot's support server
