### ISSUE TITLE
open source the bot

### ISSUE THREAD

**Issue by FurblandChannel** [TheNoob27/starboard-issues#23]
I don’t like the latest update and I want to host an older version, is this possible?

**Comment by ghostlylake** [comment]
There are no current plans to make Starboard open-source.  However, you are more than welcome to share what you don't like about the current version - feedback is always appreciated and may be acted upon if deemed reasonable.

**Comment by FurblandChannel** [comment]
ah, I dislike the new slash commands (I just find discord’s interface for them clunky and cumbersome), my proposal (a lot of big-name bots have done this) is you implement both command forms alongside each other
