### ISSUE TITLE
Enhancement: Proper Tenor GIF Support

### ISSUE THREAD

**Issue by AstreaTSS** [TheNoob27/starboard-issues#5]
If you thought I was done... honestly yeah but I just got this idea today.

Anyways, currently, GIFs with Tenor (and so Discord GIFs) are actually displayed due to the fact that they create a GIFV embed (and the bot has embed support). However, currently, it only gets the thumbnail of the GIF, and doesn't get the GIF itself.

It would be nice, if even possible, if the actual GIF were displayed. This would probably require use of Tenor's REST API, which is definitely not easy, but still.

**Comment by TheNoob27** [comment]
Yeah currently, of all the links tenor provide to discord via the embed, none of them can give me the actual gif so i have to just display a thumbnail and let users click on the link the user sent. Maybe I look into it but for now I don't think it's a big issue

**Comment by circuitsacul** [comment]
I managed to succesfully implement this in my bot, it really isn't that hard.

You just need to get the gifID from the URL, and then the .gif URL from the API.

https://github.com/CircuitsBots/Starboard/blob/master/api/tenor.py

**Comment by AstreaTSS** [comment]
Yep, more or less how I did it. Although that does introduce some questions like how often would this happen and would it exceed free API limits.
