### ISSUE TITLE
Enhancement: Create an option to disable commands. 

### ISSUE THREAD

**Issue by Hoi0007** [TheNoob27/starboard-issues#6]
Some commands like star explore can be annoying, personally I dont find them annoying but many moderators of my server claim that it gets annoying when people start using star explore and look at stuff that has no relation to our server. Star leaderboard also is supposedly annoying, since it makes it a competition(?) FFS Imma de-mod them all if they continue with this "annoying" shit.

**Comment by TheNoob27** [comment]
Okay so the **NoExplore** setting exists, it disables the explore command for you, and i was gonna make a **NoLeaderboard** setting that disables various commands but now you spoiled the surprise :(

**Comment by TheNoob27** [comment]
I've added the NoLeaderboard setting which disabled various leaderboard commands, but other than that i think that's all

**Comment by circuitsacul** [comment]
If you create a new table (say `disabledcmds`) and added and id to ever command, it would be very easy to add a custom check with the command id. (Maybe it's only this easy in discord.py, though I highly doubt that)

**Comment by TheNoob27** [comment]
i've uh
i've done this 😎😎
