### ISSUE TITLE
Enhancement: Add a setting that removes previous reward roles

### ISSUE THREAD

**Issue by Hoi0007** [TheNoob27/starboard-issues#7]
It could be really dumb when you ping a role like **@Stars** and you meant it for people with **only** that reward role. For example a message like  "Message for **@[Insert 1st Reward Role Here]**; In order to participate in this giveaway you need to collect 10 stars"

**Comment by TheNoob27** [comment]
That is actually one of the pinned messages in #suggestions, meaning that it's a good idea and i'll try working on it

Basically, sure

**Comment by TheNoob27** [comment]
Done
